[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = { FEATURES = "${{FEATURES}}", DOMAIN = "${{DOMAIN}}", TITLE = "${{TITLE}}", DESCRIPTION = "${{DESCRIPTION}}", KEYWORDS = "${{KEYWORDS}}", ACCORDION_JSON = "${{ACCORDION_JSON}}", TELEGRAM_BOT_LOGIN = "${{TELEGRAM_BOT_LOGIN}}", YANDEX_CLIENT_ID = "${{YANDEX_CLIENT_ID}}", LOGO_URL = "${{LOGO_URL}}", FAVICON_URL = "${{FAVICON_URL}}", ICON512_MASKABLE_URL = "${{ICON512_MASKABLE_URL}}", ICON512_ROUNDED_URL = "${{ICON512_ROUNDED_URL}}", THEME = "${{THEME}}", COLOR_PRIMARY_BG = "${{COLOR_PRIMARY_BG}}", COLOR_BODY_BG = "${{COLOR_BODY_BG}}", COLOR_SECOND_BG = "${{COLOR_SECOND_BG}}", COLOR_LIGHT = "${{COLOR_LIGHT}}", COLOR_BODY = "${{COLOR_BODY}}" }

[deploy]
healthcheckPath = "/api/posts"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2
