[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = { FEATURES = "${{FEATURES}}", DOMAIN = "${{DOMAIN}}", TITLE = "${{TITLE}}", DESCRIPTION = "${{DESCRIPTION}}", KEYWORDS = "${{KEYWORDS}}", ACCORDION_JSON = "${{ACCORDION_JSON}}", TELEGRAM_BOT_LOGIN = "${{TELEGRAM_BOT_LOGIN}}", YANDEX_CLIENT_ID = "${{YANDEX_CLIENT_ID}}" }

[deploy]
healthcheckPath = "/api/posts"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2
