[package]
name = "blog-generic"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
validator = { version = "0.16.1", features = ["derive", "unic", "phone"], optional = true }

[features]
default = []