name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SITE_URL: ""
      JWT_SECRET: ""
      SERVER_ADDRESS: ""
      PG_URL: ""
      TELEGRAM_BOT_TOKEN: ""

      TELEGRAM_BOT_LOGIN: ""
      TITLE: ""
      DESCRIPTION: ""
      KEYWORDS: ""
      ACCORDION_JSON: ""

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
