name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    env:
      SITE_URL: ""
      JWT_SECRET: ""
      SERVER_ADDRESS: ""
      PG_URL: ""
      RABBIT_URL: ""
      TELEGRAM_BOT_TOKEN: ""
      OPENAI_API_KEY: ""

      TELEGRAM_BOT_LOGIN: ""
      TITLE: ""
      DESCRIPTION: ""
      KEYWORDS: ""
      ACCORDION_JSON: ""

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --all-features

