name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    env:
      SITE_URL: ""
      JWT_SECRET: ""
      SERVER_ADDRESS: ""
      PG_URL: ""
      RABBIT_URL: ""
      TELEGRAM_BOT_TOKEN: ""
      OPENAI_API_KEY: ""

      TELEGRAM_BOT_LOGIN: ""
      IMAGES_PROCESSOR_URL: ""
      TITLE: ""
      DESCRIPTION: ""
      KEYWORDS: ""
      ACCORDION_JSON: ""

    steps:
    - uses: actions/checkout@v4
    - name: Fetch blog-ui
      run: make blog-ui
    - name: Run tests
      run: cargo test -p blog-server-api --verbose --no-default-features -F $(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.name == "blog-server-api") | .features | keys[]' | grep -v "lang_en" | tr '\n' ',' | sed 's/,$//')

